version: "3"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOCKER=database
      #- MONGODB_URI=
    depends_on:
      - database
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    logging:
      driver: none
volumes:
  mongodb_data_container: