openapi: "3.0.0"
info:
  description: "This is the API for Zitation app.  You can find out more about this app in [project wiki](#)."
  version: "1.0.0"
  title: "Zitation API"
  contact:
    email: "757024@unizar.es"
servers:
  - url: "https://stw-zitation.herokuapp.com/api"
    description: Production server
tags:
  - name: "User"
    description: "Operations about users"
  - name: "Company"
    description: "Operations about companies"
  - name: "HealthZone"
    description: "Operations about health zones from Zaragoza"
paths:
  /users/register:
    post:
      tags:
        - "User"
      summary: "Add a new user to the database"
      requestBody:
        description: "User object to be added to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User_register"
      responses:
        "200":
          description: "User created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_registered'
        "422":
          description: "Wrong email format"
        "405":
          description: "Wrong json format, check docs for further info /api-docs"
  /users/login:
    post:
      tags:
        - "User"
      summary: "Retrieve security token of an user"
      requestBody:
        description: "User email and password to retrieve security token"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User_login"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User_retrieved"
          links:
            token:
              operationId: updateUser, deleteUser
        "401":
          description: "Incorrect login"
        "404":
          description: "User not found"
  /users/update/{email}:
    patch:
      operationId: updateUser
      security:
        - bearerAuth: []
      tags:
        - "User"
      summary: "Update user data"
      parameters:
        - in: "path"
          name: "email"
          description: "Email address of user to update"
          required: true
          schema:
            type: string
            format: email
      requestBody:
        description: "User data to change"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User_update"
      responses:
        "200":
          description: "User updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User_registered'
        "401":
          description: "Error: Unauthorized"
        "404":
          description: "User not found"
  /users/delete/{email}:
    delete:
      operationId: deleteUser
      security:
        - bearerAuth: []
      tags:
        - "User"
      summary: "Delete an user"
      parameters:
        - in: path
          name: "email"
          description: "Email address of user to delete"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "User deleted"
        "401":
          description: "Error: Unauthorized"
        "404":
          description: "User not found"
  /companies/register:
    post:
      tags:
        - "Company"
      summary: "Add a new company to the database"
      requestBody:
        description: "Company object to be added to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company_register"
      responses:
        "200":
          description: "Company created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company_registered'
        "422":
          description: "Wrong email format"
        "405":
          description: "Wrong json format, check docs for further info /api-doc"
  /companies/login:
    post:
      tags:
        - "Company"
      summary: "Retrieve security token of a company"
      requestBody:
        description: "Company nif and password to retrieve security token"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company_login"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User_retrieved"
          links:
            token:
              operationId: updateCompany, deleteCompany
        "401":
          description: "Incorrect login"
        "404":
          description: "Company not found"
  /companies/update/{nif}:
    patch:
      operationId: updateCompany
      security:
        - bearerAuth: []
      tags:
        - "Company"
      summary: "Update company data"
      parameters:
        - in: "path"
          name: "nif"
          description: "Nif number of company to update"
          required: true
          schema:
            type: string
      requestBody:
        description: "Company data to change"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company_update"
      responses:
        "200":
          description: "Company updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company_registered'
        "401":
          description: "Error: Unauthorized"
        "404":
          description: "Company not found"
  /companies/delete/{nif}:
    delete:
      operationId: deleteCompany
      security:
        - bearerAuth: []
      tags:
        - "Company"
      summary: "Delete a company"
      parameters:
        - in: path
          name: "nif"
          description: "nif number of company to delete"
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Company deleted"
        "401":
          description: "Error: Unauthorized"
        "404":
          description: "Company not found"
  /healthzone:
    get:
      operationId: getAllHealhzone
      tags:
        - "HealthZone"
      responses:
        "200":
          description: "Receive all basic health zone information from Zaragoza"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthZoneData'
        "404":
          description: "No health zones data found"
        "500":
          description: "Internal server error, something went wrong while searching for Health Zones"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User_register:
      type: object
      properties:
        phone:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - phone
        - first_name
        - last_name
        - email
        - password
    User_registered:
      type: object
      properties:
        phone:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        salt:
          type: string
      required:
        - phone
        - first_name
        - last_name
        - password
        - salt
    User_login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    User_retrieved:
      type: object
      properties:
        success:
          type: boolean
        token:
          type: string
        expiresIn:
          type: string
    User_update:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
    Company_register:
      type: object
      properties:
        nif:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        location:
          type: object
          properties:
            alt:
              type: integer
            long:
              type: integer
      required:
        - nif
        - name
        - password
        - location
    Company_registered:
      type: object
      properties:
        nif:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        salt:
          type: string
        location:
          type: object
          properties:
            alt:
              type: integer
            long:
              type: integer
      required:
        - nif
        - name
        - password
        - location
        - salt
    Company_login:
      type: object
      properties:
        nif:
          type: string
        password:
          type: string
      required:
        - nif
        - password
    Company_update:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        salt:
          type: string
        location:
          type: object
          properties:
            alt:
              type: integer
            long:
              type: integer
    HealthZoneData:
      type: Object
      properties:
        name:
          type: String
        newcases:
          type: integer
        percentage:
          type: float
        ZBSwithCases:
          type: integer
        radius:
          type: integer


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"